Update Honeygain.yml

diff --git a/.github/workflows/Honeygain.yml b/.github/workflows/Honeygain.yml
--- a/.github/workflows/Honeygain.yml
+++ b/.github/workflows/Honeygain.yml
@@ -1,9 +1,6 @@
 name: Run Honeygain
 
 on:
-  push:
-    branches:
-      - main
   schedule:
     - cron: '0 */6 * * *'  # Run every 6 hours
 
@@ -14,7 +11,12 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
-    
+      
     - name: Run Honeygain container
       run: |
-        docker run honeygain/honeygain -tou-accept -email legendgamingyt835@gmail.com -pass L@bin123890 -device DEVICE_NAME
+        if docker run honeygain/honeygain -tou-accept -email legendgamingyt835@gmail.com -pass L@bin123890 -device DEVICE_NAME; then
+          echo "Honeygain container ran successfully"
+        else
+          echo "API Error: Network Unusable - Check your network connection"
+          exit 1
+        fi
